import type { Metadata } from "next";
import "./globals.css";
import GoogleAnalytics from "./GoogleAnalytics";

const siteUrl = "https://dlawasfun.vercel.app";
const socialImagePath = "/og-social-dlawasfun-360.png";
const socialImageUrl = `${siteUrl}${socialImagePath}`;
const seoTitle = "Fotobudka 360 Mazury | Giżycko, Olsztyn, Ełk | dlawas.fun";
const seoDescription = "Fotobudka 360 na Mazurach: Giżycko, Olsztyn, Ełk, Mikołajki, Mrągowo i okolice. Wesela, eventy, DJ i kompleksowa oprawa imprez dlawas.fun w całej Polsce.";

const warmiaMazuryCities = [
  "Olsztyn",
  "Elbląg",
  "Ełk",
  "Giżycko",
  "Mikołajki",
  "Ryn",
  "Mrągowo",
  "Iława",
  "Ostróda",
  "Kętrzyn",
  "Bartoszyce",
  "Szczytno",
  "Działdowo",
  "Pisz",
  "Braniewo",
  "Lidzbark Warmiński",
  "Olecko",
  "Gołdap",
  "Nidzica",
  "Morąg",
  "Węgorzewo",
  "Pasłęk",
  "Nowe Miasto Lubawskie",
  "Biskupiec",
  "Lubawa",
  "Dobre Miasto",
  "Orneta",
  "Lidzbark",
  "Olsztynek",
  "Barczewo",
  "Susz",
  "Orzysz",
  "Reszel",
  "Ruciane-Nida",
  "Korsze",
  "Górowo Iławeckie",
  "Biała Piska",
  "Tolkmicko",
  "Frombork",
  "Zalewo",
  "Miłomłyn",
  "Pasym",
  "Jeziorany",
  "Sępopol",
  "Bisztynek",
  "Miłakowo",
  "Kisielice",
] as const;

const majorPolishCities = [
  "Warszawa",
  "Kraków",
  "Wrocław",
  "Łódź",
  "Poznań",
  "Gdańsk",
  "Szczecin",
  "Lublin",
  "Bydgoszcz",
  "Białystok",
  "Katowice",
  "Gdynia",
  "Częstochowa",
  "Rzeszów",
  "Radom",
  "Toruń",
  "Sosnowiec",
  "Kielce",
  "Gliwice",
  "Olsztyn",
  "Bielsko-Biała",
  "Bytom",
  "Zabrze",
  "Zielona Góra",
  "Rybnik",
  "Ruda Śląska",
  "Opole",
  "Tychy",
  "Gorzów Wielkopolski",
  "Dąbrowa Górnicza",
  "Elbląg",
  "Płock",
  "Koszalin",
  "Wałbrzych",
  "Tarnów",
  "Włocławek",
  "Chorzów",
  "Kalisz",
  "Legnica",
  "Grudziądz",
  "Jaworzno",
  "Słupsk",
  "Jastrzębie-Zdrój",
  "Nowy Sącz",
  "Jelenia Góra",
  "Siedlce",
  "Mysłowice",
  "Piła",
  "Konin",
  "Piotrków Trybunalski",
  "Lubin",
  "Inowrocław",
  "Ostrów Wielkopolski",
  "Suwałki",
  "Stargard",
  "Gniezno",
  "Pruszków",
  "Ostrowiec Świętokrzyski",
  "Siemianowice Śląskie",
  "Głogów",
  "Pabianice",
  "Leszno",
  "Żory",
  "Zamość",
  "Łomża",
  "Chełm",
  "Ełk",
  "Przemyśl",
  "Mielec",
  "Biała Podlaska",
  "Tarnowskie Góry",
  "Bełchatów",
  "Świdnica",
  "Będzin",
  "Zgierz",
  "Racibórz",
  "Legionowo",
  "Piekary Śląskie",
  "Wejherowo",
  "Rumia",
  "Starachowice",
  "Świętochłowice",
  "Skierniewice",
  "Wodzisław Śląski",
  "Starogard Gdański",
  "Puławy",
  "Kędzierzyn-Koźle",
  "Tarnobrzeg",
  "Kołobrzeg",
  "Krosno",
  "Radomsko",
  "Otwock",
  "Skarżysko-Kamienna",
  "Ciechanów",
  "Nysa",
  "Zduńska Wola",
  "Świnoujście",
  "Bolesławiec",
  "Dębica",
  "Nowa Sól",
] as const;

const nationwideServiceAreas = [...new Set(["Polska", "Mazury", ...warmiaMazuryCities, ...majorPolishCities])];

const localSeoKeywords = warmiaMazuryCities.flatMap((city) => [
  `fotobudka ${city}`,
  `fotobudka 360 ${city}`,
]);

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: seoTitle,
  description: seoDescription,
  applicationName: "dlawas.fun | Fotobudka 360 Mazury",
  authors: [{ name: "dlawas.fun", url: "https://www.dlawas.fun/" }],
  creator: "dlawas.fun",
  publisher: "dlawas.fun",
  category: "Oprawa imprez i fotobudka 360",
  keywords: [
    "fotobudka",
    "fotobudka 360",
    "fotobudka Mazury",
    "fotobudka 360 Mazury",
    "oprawa imprez Mazury",
    "DJ na imprezę",
    "DJ Giżycko",
    "DJ Olsztyn",
    "DJ Ełk",
    "DJ Mikołajki",
    "wesele Mazury",
    "fotobudka 360 Polska",
    "oprawa imprez Polska",
    "dlawasfun",
    "dlawas.fun",
    "dlawasfun Mazury",
    "dlawasfun Polska",
    "dlawasfun fotobudka 360",
    "dlawasfun DJ i wodzirej",
    ...localSeoKeywords,
  ],
  alternates: {
    canonical: "/",
    languages: { "pl-PL": "/" },
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    title: seoTitle,
    description: seoDescription,
    type: "website",
    url: "/",
    siteName: "dlawas.fun",
    locale: "pl_PL",
    images: [
      {
        url: socialImagePath,
        width: 1730,
        height: 909,
        alt: "dlawas.fun i Fotobudka 360 na Mazurach",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: seoTitle,
    description: seoDescription,
    images: [socialImagePath],
  },
  other: {
    "geo.region": "PL-28",
    "geo.placename": "Giżycko, Mazury",
    "geo.position": "54.038;21.769",
    ICBM: "54.038, 21.769",
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon-48.png", sizes: "48x48", type: "image/png" },
      { url: "/favicon.png", sizes: "512x512", type: "image/png" },
    ],
    shortcut: "/favicon.png",
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

const organizationJsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${siteUrl}/#organization`,
      name: "dlawas.fun",
      alternateName: "dlawasfun",
      url: siteUrl,
      logo: `${siteUrl}/google-logo.png`,
      image: socialImageUrl,
      telephone: "+48 780 059 216",
      email: "kontakt@dlawas.fun",
      description: seoDescription,
      areaServed: nationwideServiceAreas,
      knowsAbout: [
        "Fotobudka 360",
        "DJ i wodzirej",
        "Oprawa muzyczna wesel i eventów",
        "Nagłośnienie i oświetlenie imprez",
        "Organizacja atrakcji eventowych",
      ],
      contactPoint: {
        "@type": "ContactPoint",
        telephone: "+48 780 059 216",
        email: "kontakt@dlawas.fun",
        contactType: "customer service",
        areaServed: "PL",
        availableLanguage: "Polish",
      },
      sameAs: [
        "https://www.dlawas.fun/",
        "https://www.instagram.com/dlawas.fun/",
        "https://www.facebook.com/p/Dlawasfun-61572704770269/",
      ],
    },
    {
      "@type": "EntertainmentBusiness",
      "@id": `${siteUrl}/#localbusiness`,
      name: "dlawas.fun | Fotobudka 360 i oprawa imprez",
      alternateName: ["dlawasfun", "dlawas.fun", "Fotobudka 360 Mazury"],
      url: siteUrl,
      logo: `${siteUrl}/google-logo.png`,
      image: socialImageUrl,
      description: seoDescription,
      telephone: "+48 780 059 216",
      email: "kontakt@dlawas.fun",
      priceRange: "$$",
      address: {
        "@type": "PostalAddress",
        streetAddress: "3 Maja 11",
        postalCode: "19-500",
        addressLocality: "Giżycko",
        addressRegion: "warmińsko-mazurskie",
        addressCountry: "PL",
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: 54.038,
        longitude: 21.769,
      },
      parentOrganization: { "@id": `${siteUrl}/#organization` },
      areaServed: nationwideServiceAreas.map((city) => city === "Polska" || city === "Mazury"
        ? { "@type": "AdministrativeArea", name: city }
        : { "@type": "City", name: city }),
      hasOfferCatalog: {
        "@type": "OfferCatalog",
        name: "Fotobudka 360 i oprawa wydarzeń",
        itemListElement: [
          "Fotobudka 360",
          "DJ i wodzirej",
          "Nagłośnienie",
          "Oświetlenie dekoracyjne",
          "Fontanny iskier",
          "Ciężki dym",
          "Saksofonista",
          "Napis LOVE",
        ].map((name) => ({ "@type": "Offer", itemOffered: { "@type": "Service", name } })),
      },
      sameAs: [
        "https://www.dlawas.fun/",
        "https://www.instagram.com/dlawas.fun/",
        "https://www.facebook.com/p/Dlawasfun-61572704770269/",
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${siteUrl}/#website`,
      url: siteUrl,
      name: "Fotobudka 360 Mazury | dlawas.fun",
      alternateName: "dlawas.fun",
      inLanguage: "pl-PL",
      publisher: { "@id": `${siteUrl}/#organization` },
    },
    {
      "@type": "WebPage",
      "@id": `${siteUrl}/#webpage`,
      url: siteUrl,
      name: seoTitle,
      description: seoDescription,
      inLanguage: "pl-PL",
      isPartOf: { "@id": `${siteUrl}/#website` },
      about: { "@id": `${siteUrl}/#organization` },
      primaryImageOfPage: { "@type": "ImageObject", url: socialImageUrl, width: 1730, height: 909 },
    },
    {
      "@type": "Service",
      "@id": `${siteUrl}/#fotobudka-360`,
      name: "Fotobudka 360 Mazury",
      serviceType: "Fotobudka 360 na wesela, eventy i imprezy",
      image: `${siteUrl}/media/services/fotobudka-360.png`,
      provider: { "@id": `${siteUrl}/#localbusiness` },
      areaServed: nationwideServiceAreas.map((name) => ({ "@type": name === "Polska" || name === "Mazury" ? "AdministrativeArea" : "City", name })),
      url: `${siteUrl}/#jak-to-dziala`,
    },
    {
      "@type": "Service",
      "@id": `${siteUrl}/#oprawa-imprez`,
      name: "DJ i oprawa imprez na Mazurach",
      serviceType: "DJ, wodzirej, nagłośnienie i oświetlenie imprez",
      provider: { "@id": `${siteUrl}/#localbusiness` },
      areaServed: nationwideServiceAreas.map((name) => ({ "@type": name === "Polska" || name === "Mazury" ? "AdministrativeArea" : "City", name })),
      url: `${siteUrl}/#wiecej-o-nas`,
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" data-scroll-behavior="smooth">
      <body className="antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        {children}
      </body>
      <GoogleAnalytics />
    </html>
  );
}
